services:
  db_poseidon:
    image: mysql:5.7.44
    container_name: db_poseidon
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - db_poseidon:/var/lib/mysql
      - ./datos/poseidon:/docker-entrypoint-initdb.d
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - coma_network
    command: --max_allowed_packet=32505856 && ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '1234';
  db_ffm:
    image: mysql:5.7.44
    container_name: db_ffm
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - db_ffm:/var/lib/mysql
      - ./datos/ffm:/docker-entrypoint-initdb.d
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - coma_network
    command: --max_allowed_packet=32505856 && ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '1234';
  coma_ep:
    depends_on:
      - db_poseidon
      - db_ffm
    image: untetheredj/coma:latest
    container_name: coma_eim
    #ports:
    #  - "9000:8080"
    volumes:
      - ./webapps/eisi.war:/datadrive/tomcat/webapps/eisi.war
      - ./archivos/eg/css:/datadrive/tomcat/datos/css
      - ./archivos/eg/archivosDatadrive:/datadrive/tomcat/datos/archivosDatadrive
      - ./archivos/eg/Archivos:/datadrive/tomcat/datos/Archivos
      - ./archivos/eg/ArchivosProfesores:/datadrive/tomcat/datos/ArchivosProfesores
      - ./archivos/eg/WebProfesor:/datadrive/tomcat/datos/WebProfesor
      - ./archivos/eg/grupo:/datadrive/tomcat/datos/grupo
      - ./archivos/eg/images:/datadrive/tomcat/datos/images
      - ./archivos/eg/Profesores:/datadrive/tomcat/datos/Profesores
      - ./startup.sh:/datadrive/tomcat/startup.sh
    networks:
      - coma_network
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      DIAMANTE_DNS: "db_ffm"
      POSEIDON_DNS: "db_poseidon"
      DATABASE_NAME: "diamante"
      NOMBRE_ESCUELA: "Escuela de Geología"
      NOMBRE_ABREVIADO: "ESGEO"
      PROGRAMA_PREGRADO: "34"
      CODIGO_ESCUELA: "6560"
      POSGRADO_1: "217"
      POSGRADO_2: "314"
      POSGRADO_3: "339"
      POSGRADO_4: "361"
      POSGRADO_5: "362"
      POSGRADO_6: "338"
      POSGRADO_7: "99999"
      POSGRADO_8: "99999"
    command: bash -c "chmod +x /datadrive/tomcat/startup.sh && /bin/bash /datadrive/tomcat/startup.sh"
  coma_eip:
    depends_on:
      - db_poseidon
      - db_ffm
    image: untetheredj/coma:latest
    container_name: coma_eip
    #ports:
    #  - "9001:8080"
    volumes:
      - ./webapps/eisi.war:/datadrive/tomcat/webapps/eisi.war
      - ./archivos/eip/css:/datadrive/tomcat/datos/css
      - ./archivos/eip/archivosDatadrive:/datadrive/tomcat/datos/archivosDatadrive
      - ./archivos/eip/Archivos:/datadrive/tomcat/datos/Archivos
      - ./archivos/eip/ArchivosProfesores:/datadrive/tomcat/datos/ArchivosProfesores
      - ./archivos/eip/WebProfesor:/datadrive/tomcat/datos/WebProfesor
      - ./archivos/eip/grupo:/datadrive/tomcat/datos/grupo
      - ./archivos/eip/images:/datadrive/tomcat/datos/images
      - ./archivos/eip/Profesores:/datadrive/tomcat/datos/Profesores
      - ./startup.sh:/datadrive/tomcat/startup.sh
    networks:
      - coma_network
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      DIAMANTE_DNS: "db_ffm"
      POSEIDON_DNS: "db_poseidon"
      DATABASE_NAME: "diamante"
      NOMBRE_ESCUELA: "Escuela de Ingeniería de Petróleos"
      NOMBRE_ABREVIADO: "EISI"
      PROGRAMA_PREGRADO: "11"
      CODIGO_ESCUELA: "6570"
      POSGRADO_1: "302"
      POSGRADO_2: "224"
      POSGRADO_3: "99999"
      POSGRADO_4: "99999"
      POSGRADO_5: "99999"
      POSGRADO_6: "99999"
      POSGRADO_7: "99999"
      POSGRADO_8: "99999"
    command: bash -c "chmod +x /datadrive/tomcat/startup.sh && /bin/bash /datadrive/tomcat/startup.sh"
volumes:
  db_poseidon:
    external: false
  db_ffm:
    external: false
networks:
  coma_network:
    driver: bridge
    name: coma_network