services:
  poseidon:
    image: mysql:latest
    container_name: poseidon
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - poseidon:/var/lib/mysql
      - ./datos/poseidon:/docker-entrypoint-initdb.d
    networks:
      - coma_network
    command: --default-authentication-plugin=mysql_native_password
  eim_diamante:
    image: mysql:latest
    container_name: eim_diamante
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - eim_diamante:/var/lib/mysql
      - ./datos/eim:/docker-entrypoint-initdb.d
    networks:
      - coma_network
    command: --default-authentication-plugin=mysql_native_password
  eip_diamante:
    image: mysql:latest
    container_name: eip_diamante
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - eip_diamante:/var/lib/mysql
      - ./datos/eip:/docker-entrypoint-initdb.d
    networks:
      - coma_network
    command: --default-authentication-plugin=mysql_native_password
  coma_eim:
    depends_on:
      - poseidon
      - eim_diamante
    image: tomcat:9.0.87
    container_name: coma_eim
    ports:
      - "9000:8080"
    volumes:
      - ./webapps/eisi.war:/usr/local/tomcat/webapps/eisi.war
      - ./archivos/eim/css:/usr/local/tomcat/datos
      - ./startup.sh:/usr/local/tomcat/startup.sh
    networks:
      - coma_network
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      DIAMANTE_DNS: "eim_diamante"
      NOMBRE_ESCUELA: "Escuela de Ingeniería Mecánica"
      NOMBRE_ABREVIADO: "EIM"
      PROGRAMA_PREGRADO: "24"
      CODIGO_ESCUELA: "6560"
      POSGRADO_1: "217"
      POSGRADO_2: "314"
      POSGRADO_3: "339"
      POSGRADO_4: "361"
      POSGRADO_5: "362"
      POSGRADO_6: "338"
      POSGRADO_7: "99999"
      POSGRADO_8: "99999"
    command: "/bin/bash /usr/local/tomcat/startup.sh"
  coma_eip:
    depends_on:
      - poseidon
      - eip_diamante
    image: tomcat:9.0.87
    container_name: coma_eip
    ports:
      - "9001:8080"
    volumes:
      - ./webapps/eisi.war:/usr/local/tomcat/webapps/eisi.war
    networks:
      - coma_network
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      DIAMANTE_DNS: "eip_diamante"
      NOMBRE_ESCUELA: "Escuela de Ingeniería de Petróleos"
      NOMBRE_ABREVIADO: "EISI"
      PROGRAMA_PREGRADO: "11"
      CODIGO_ESCUELA: "6570"
      POSGRADO_1: "302"
      POSGRADO_2: "224"
      POSGRADO_3: "99999"
      POSGRADO_4: "99999"
      POSGRADO_5: "99999"
      POSGRADO_6: "99999"
      POSGRADO_7: "99999"
      POSGRADO_8: "99999"
volumes:
  poseidon:
    external: false
  eip_diamante:
    external: false
  eim_diamante:
    external: false
  eim_css:
    driver: local
  eip_css:
    driver: local
networks:
  coma_network:
    driver: bridge
    name: coma_network