module.exports = {
  EISI: {
    schoolName: 'sistemas',
    host: 'db_ffm',
    port: 3306,
    db: 'diamante_eisi',
    user: process.env.DB_SQL_USER,
    pass: process.env.DB_SQL_PASSWORD,
  },
  FIFME: {
    schoolName: 'fisicomecanicas',
    host: 'db_ffm',
    port: 3306,
    db: 'diamante_fifme',
    user: process.env.DB_SQL_USER,
    pass: process.env.DB_SQL_PASSWORD,
  },
  EDI: {
    schoolName: 'disindustrial',
    host: 'db_ffm',
    port: 3306,
    db: 'diamante_edi',
    user: process.env.DB_SQL_USER,
    pass: process.env.DB_SQL_PASSWORD,
  },
  FIFQUI: {
    schoolName: 'fisicoquimicas',
    host: 'db_ffq',
    port: 3306,
    db: 'diamante_fifqui',
    user: process.env.DB_SQL_USER,
    pass: process.env.DB_SQL_PASSWORD,
  },
  TRS: {
    schoolName: 'trabajosocial',
    host: 'db_fch',
    port: 3306,
    db: 'diamante_trs',
    user: process.env.DB_SQL_USER,
    pass: process.env.DB_SQL_PASSWORD,
  },
  FCH: {
    schoolName: 'humanas',
    host: 'db_fch',
    port: 3306,
    db: 'diamante_fch',
    user: process.env.DB_SQL_USER,
    pass: process.env.DB_SQL_PASSWORD,
  },
  VAC: {
    schoolName: 'vacadem',
    host: 'db_otros',
    port: 3306,
    db: 'diamante_vac',
    user: process.env.DB_SQL_USER,
    pass: process.env.DB_SQL_PASSWORD,
  },
  ESFIS: {
    schoolName: 'fisica',
    host: 'db_fcie',
    port: 3306,
    db: 'diamante_esfis',
    user: process.env.DB_SQL_USER,
    pass: process.env.DB_SQL_PASSWORD,
  },
  CIE: {
    schoolName: 'ciencias',
    host: 'db_fcie',
    port: 3306,
    db: 'diamante_cie',
    user: process.env.DB_SQL_USER,
    pass: process.env.DB_SQL_PASSWORD,
  },
  ESQUIM: {
    schoolName: 'quimica',
    host: 'db_fcie',
    port: 3306,
    db: 'diamante_esquim',
    user: process.env.DB_SQL_USER,
    pass: process.env.DB_SQL_PASSWORD,
  },
  ECI: {
    schoolName: 'civil',
    host: 'db_ffm',
    port: 3306,
    db: 'diamante_eci',
    user: process.env.DB_SQL_USER,
    pass: process.env.DB_SQL_PASSWORD,
  },
  ESMED: {
    schoolName: 'medicina',
    host: 'db_fs',
    port: 3306,
    db: 'diamante_esmed',
    user: process.env.DB_SQL_USER,
    pass: process.env.DB_SQL_PASSWORD,
  },
  EM: {
    schoolName: 'microbiologia',
    host: 'db_fs',
    port: 3306,
    db: 'diamante_em',
    user: process.env.DB_SQL_USER,
    pass: process.env.DB_SQL_PASSWORD,
  },
  HIS: {
    schoolName: 'historia',
    host: 'db_fch',
    port: 3306,
    db: 'diamante_his',
    user: process.env.DB_SQL_USER,
    pass: process.env.DB_SQL_PASSWORD,
  },
  MAT: {
    schoolName: 'matematicas',
    host: 'db_fcie',
    port: 3306,
    db: 'diamante_mat',
    user: process.env.DB_SQL_USER,
    pass: process.env.DB_SQL_PASSWORD,
  },
  BIO: {
    schoolName: 'biologia',
    host: 'db_fcie',
    port: 3306,
    db: 'diamante_bio',
    user: process.env.DB_SQL_USER,
    pass: process.env.DB_SQL_PASSWORD,
  },
  IDIO: {
    schoolName: 'idiomas',
    host: 'db_fch',
    port: 3306,
    db: 'diamante_idio',
    user: process.env.DB_SQL_USER,
    pass: process.env.DB_SQL_PASSWORD,
  },
  EEIE: {
    schoolName: 'industrial',
    host: 'db_ffm',
    port: 3306,
    db: 'diamante_eeie',
    user: process.env.DB_SQL_USER,
    pass: process.env.DB_SQL_PASSWORD,
  },
  EDER: {
    schoolName: 'derecho',
    host: 'db_fch',
    port: 3306,
    db: 'diamante_eder',
    user: process.env.DB_SQL_USER,
    pass: process.env.DB_SQL_PASSWORD,
  },
  EART: {
    schoolName: 'artes',
    host: 'db_fch',
    port: 3306,
    db: 'diamante_eart',
    user: process.env.DB_SQL_USER,
    pass: process.env.DB_SQL_PASSWORD,
  },
  E2ECON: {
    schoolName: 'economia',
    host: 'db_fch',
    port: 3306,
    db: 'diamante_e2con',
    user: process.env.DB_SQL_USER,
    pass: process.env.DB_SQL_PASSWORD,
  },
  EFIS: {
    schoolName: 'fisioterapia',
    host: 'db_fs',
    port: 3306,
    db: 'diamante_efis',
    user: process.env.DB_SQL_USER,
    pass: process.env.DB_SQL_PASSWORD,
  },
  ESFIL: {
    schoolName: 'filosofia',
    host: 'db_fch',
    port: 3306,
    db: 'diamante_esfil',
    user: process.env.DB_SQL_USER,
    pass: process.env.DB_SQL_PASSWORD,
  },
  ESENF: {
    schoolName: 'enfermeria',
    host: 'db_fs',
    port: 3306,
    db: 'diamante_esenf',
    user: process.env.DB_SQL_USER,
    pass: process.env.DB_SQL_PASSWORD,
  },
  EDU: {
    schoolName: 'educacion',
    host: 'db_fch',
    port: 3306,
    db: 'diamante_edu',
    user: process.env.DB_SQL_USER,
    pass: process.env.DB_SQL_PASSWORD,
  },
  NUTRI: {
    schoolName: 'nutricion',
    host: 'db_fs',
    port: 3306,
    db: 'diamante_nutri',
    user: process.env.DB_SQL_USER,
    pass: process.env.DB_SQL_PASSWORD,
  },
  EIM: {
    schoolName: 'mecanica',
    host: 'db_ffm',
    port: 3306,
    db: 'diamante_eim',
    user: process.env.DB_SQL_USER,
    pass: process.env.DB_SQL_PASSWORD,
  },
  EIP: {
    schoolName: 'petroleos',
    host: 'db_ffm',
    port: 3306,
    db: 'diamante_eip',
    user: process.env.DB_SQL_USER,
    pass: process.env.DB_SQL_PASSWORD,
  },
  EIQ: {
    schoolName: 'ingquimica',
    host: 'db_ffq',
    port: 3306,
    db: 'diamante_eiq',
    user: process.env.DB_SQL_USER,
    pass: process.env.DB_SQL_PASSWORD,
  },
  EIMT: {
    schoolName: 'metalurgia',
    host: 'db_ffq',
    port: 3306,
    db: 'diamante_eimt',
    user: process.env.DB_SQL_USER,
    pass: process.env.DB_SQL_PASSWORD,
  },
  ESGEO: {
    schoolName: 'geologia',
    host: 'db_ffq',
    port: 3306,
    db: 'diamante_esgeo',
    user: process.env.DB_SQL_USER,
    pass: process.env.DB_SQL_PASSWORD,
  },
  E3T: {
    schoolName: 'e3t',
    host: 'db_ffm',
    port: 3306,
    db: 'diamante_e3t',
    user: process.env.DB_SQL_USER,
    pass: process.env.DB_SQL_PASSWORD,
  },
};
