services:
  actions-runner:
    image: untetheredj/actions-runner:latest
    container_name: actions-runner
    restart: always
    environment:
      - REPO=calumet/coma
      - TOKEN=token
      - TZ=America/Bogota
    deploy:
      resources: 
        limits:
          cpus: '0.20'
          memory: 4G
        reservations:
          memory: 3G
    volumes:
      - /datadrive/deployment:/datadrive/deployment
    command: bash -c "chown -R docker:docker /datadrive/deployment && ./start.sh"
    networks:
      - coma_network
networks:
  coma_network:
    driver: bridge
    name: coma_network
