services:
  ngix:
    image: nginx:1.27.1
    restart: always
    container_name: nginx
    volumes:
      - ../config/nginx/app.conf:/etc/nginx/conf.d/app.conf:ro
      - ../config/nginx/include/:/etc/nginx/conf.d/include/:ro
      - ../certbot/www/:/var/www/certbot/:ro
      - ../certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - coma_network
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ../certbot/www/:/var/www/certbot/:rw
      - ../certbot/conf/:/etc/letsencrypt/:rw
    networks:
      - coma_network
networks:
  coma_network:
    driver: bridge
    name: coma_network