services:
  ngix:
    image: nginx:1.27.1
    restart: unless-stopped
    container_name: nginx
    volumes:
      - ./config/nginx/app.conf:/etc/nginx/conf.d/app.conf:rw
      - ./certbot/www/:/var/www/certbot/:rw
    ports:
      - "80:80"
      - "443:443"
    networks:
      - coma_network
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
networks:
  coma_network:
    driver: bridge
    name: coma_network