services:
  db_poseidon:
    image: mysql:5.7.44
    container_name: db_poseidon
    restart: on-failure:3
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=America/Bogota
    volumes:
      - db_poseidon:/var/lib/mysql
      - ../database/poseidon:/docker-entrypoint-initdb.d
      - ../config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - coma_network
    command: --max_allowed_packet=32505856 && mysql ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '1234';
  db_ffm:
    image: mysql:5.7.44
    container_name: db_ffm
    restart: on-failure:3
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=America/Bogota
    volumes:
      - db_ffm:/var/lib/mysql
      - ../database/ffm:/docker-entrypoint-initdb.d
      - ../config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - coma_network
    command: --max_allowed_packet=32505856 && mysql ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '1234';
  db_ffq:
    image: mysql:5.7.44
    container_name: db_ffq
    restart: on-failure:3
    ports:
      - "3309:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=America/Bogota
    volumes:
      - db_ffq:/var/lib/mysql
      - ../database/ffq:/docker-entrypoint-initdb.d
      - ../config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - coma_network
    command: --max_allowed_packet=32505856 && mysql ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '1234';
  db_fch:
    image: mysql:5.7.44
    container_name: db_fch
    restart: on-failure:3
    ports:
      - "3310:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=America/Bogota
    volumes:
      - db_fch:/var/lib/mysql
      - ../database/fch:/docker-entrypoint-initdb.d
      - ../config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - coma_network
    command: --max_allowed_packet=32505856 && mysql ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '1234';
  db_fcie:
    image: mysql:5.7.44
    container_name: db_fcie
    restart: on-failure:3
    ports:
      - "3311:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=America/Bogota
    volumes:
      - db_fcie:/var/lib/mysql
      - ../database/fcie:/docker-entrypoint-initdb.d
      - ../config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - coma_network
    command: --max_allowed_packet=32505856 && mysql ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '1234';
  db_fs:
    image: mysql:5.7.44
    container_name: db_fs
    restart: on-failure:3
    ports:
      - "3312:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=America/Bogota
    volumes:
      - db_fs:/var/lib/mysql
      - ../database/fs:/docker-entrypoint-initdb.d
      - ../config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - coma_network
    command: --max_allowed_packet=32505856 && mysql ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '1234';
  db_otros:
    image: mysql:5.7.44
    container_name: db_otros
    restart: on-failure:3
    ports:
      - "3313:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=America/Bogota
    volumes:
      - db_otros:/var/lib/mysql
      - ../database/otros:/docker-entrypoint-initdb.d
      - ../config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - coma_network
    command: --max_allowed_packet=32505856 && mysql ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '1234';
volumes:
  db_poseidon:
    external: false
    name: db_poseidon
  db_ffm:
    external: false
    name: db_ffm
  db_ffq:
    external: false
    name: db_ffq
  db_fch:
    external: false
    name: db_fch
  db_fcie:
    external: false
    name: db_fcie
  db_fs:
    external: false
    name: db_fs
  db_otros:
    external: false
    name: db_otros
networks:
  coma_network:
    driver: bridge
    name: coma_network