services:
  ngix:
    image: nginx:1.27.1
    restart: on-failure:3
    container_name: nginx
    volumes:
      - ../config/nginx/app.conf:/etc/nginx/conf.d/app.conf:ro
      - ../config/nginx/include/:/etc/nginx/conf.d/include/:ro
      - ../certbot/www/:/var/www/certbot/:ro
      - ../certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - "80:80"
      - "443:443"
    environment:
      TZ: America/Bogota
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - coma_network
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ../certbot/www/:/var/www/certbot/:rw
      - ../certbot/conf/:/etc/letsencrypt/:rw
    environment:
      TZ: America/Bogota
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - coma_network
networks:
  coma_network:
    driver: bridge
    name: coma_network