services:
  realtime:
    image: realtime:latest
    container_name: realtime
    volumes:
      - ../realtime/realtime:/datadrive/realtime
    environment:
    networks:
      - coma_network
    env_file:
      - ./secrets/secrets.env
networks:
  coma_network:
    driver: bridge
    name: coma_network
